// Lightweight mock data for static/demo mode. These values are only
// used in the browser build when REACT_APP_USE_MOCK is enabled or no
// API URL is provided in production.
export const mockUsers = [
  {
    _id: 'u-admin',
    id: 'u-admin',
    name: 'Alex Admin',
    email: 'admin@sheltersync.com',
    password: 'demo123',
    role: 'admin',
    location: 'Remote',
  },
  {
    _id: 'u-shelter',
    id: 'u-shelter',
    name: 'Harbor Paws Shelter',
    email: 'shelter@sheltersync.com',
    password: 'demo123',
    role: 'shelter',
    location: 'San Francisco, CA',
    phone: '(415) 555-0147',
  },
  {
    _id: 'u-adopter',
    id: 'u-adopter',
    name: 'Jamie Rivers',
    email: 'adopter@sheltersync.com',
    password: 'demo123',
    role: 'adopter',
    location: 'Seattle, WA',
  },
  {
    _id: 'u-adopter-2',
    id: 'u-adopter-2',
    name: 'Taylor Chen',
    email: 'taylor@example.com',
    password: 'demo123',
    role: 'adopter',
    location: 'Denver, CO',
  },
];

const shelterContact = {
  _id: 'u-shelter',
  id: 'u-shelter',
  name: 'Harbor Paws Shelter',
  email: 'shelter@sheltersync.com',
  phone: '(415) 555-0147',
  location: 'San Francisco, CA',
};

export const mockPets = [
  {
    _id: 'p-scout',
    id: 'p-scout',
    name: 'Scout',
    breed: 'Australian Shepherd',
    age: 2,
    adoptionStatus: 'available',
    location: 'San Francisco, CA',
    healthNotes: 'Up to date on vaccines, loves long walks.',
    imageURL: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=80',
    personality: 'Playful, smart, and energetic.',
    shelter: shelterContact,
    createdAt: '2024-06-20T12:00:00Z',
  },
  {
    _id: 'p-luna',
    id: 'p-luna',
    name: 'Luna',
    breed: 'Siberian Husky',
    age: 3,
    adoptionStatus: 'pending',
    location: 'Portland, OR',
    healthNotes: 'Spayed, microchipped, friendly with kids.',
    imageURL: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=1200&q=80',
    personality: 'Gentle, vocal, loves the snow.',
    shelter: shelterContact,
    createdAt: '2024-05-05T12:00:00Z',
  },
  {
    _id: 'p-olive',
    id: 'p-olive',
    name: 'Olive',
    breed: 'Calico Cat',
    age: 1,
    adoptionStatus: 'available',
    location: 'Seattle, WA',
    healthNotes: 'Indoor only, thrives with quiet time.',
    imageURL: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=80',
    personality: 'Curious, cuddly, and confident.',
    shelter: shelterContact,
    createdAt: '2024-07-12T12:00:00Z',
  },
  {
    _id: 'p-rio',
    id: 'p-rio',
    name: 'Rio',
    breed: 'Golden Retriever',
    age: 4,
    adoptionStatus: 'available',
    location: 'Los Angeles, CA',
    healthNotes: 'Heartworm negative, loves swimming.',
    imageURL: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=80',
    personality: 'Friendly with everyone, eager to please.',
    shelter: shelterContact,
    createdAt: '2024-04-18T12:00:00Z',
  },
  {
    _id: 'p-milo',
    id: 'p-milo',
    name: 'Milo',
    breed: 'Beagle',
    age: 5,
    adoptionStatus: 'adopted',
    location: 'San Jose, CA',
    healthNotes: 'Recently adopted, included for demo status.',
    imageURL: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=80',
    personality: 'Calm, scent-driven, couch companion.',
    shelter: shelterContact,
    createdAt: '2024-03-10T12:00:00Z',
  },
  {
    _id: 'p-finn',
    id: 'p-finn',
    name: 'Finn',
    breed: 'Mixed Breed',
    age: 2,
    adoptionStatus: 'available',
    location: 'Sacramento, CA',
    healthNotes: 'House-trained, knows basic commands.',
    imageURL: 'https://images.unsplash.com/photo-1507149833265-60c372daea22?auto=format&fit=crop&w=1200&q=80',
    personality: 'Loves hikes and car rides.',
    shelter: shelterContact,
    createdAt: '2024-06-01T12:00:00Z',
  },
];

export const mockRequests = [
  {
    _id: 'r-1',
    id: 'r-1',
    pet: mockPets[0],
    adopter: mockUsers[2],
    status: 'pending',
    message: 'We have a big yard and love to hike every weekend.',
    createdAt: '2024-07-02T12:00:00Z',
  },
  {
    _id: 'r-2',
    id: 'r-2',
    pet: mockPets[1],
    adopter: mockUsers[3],
    status: 'approved',
    message: 'Looking for a companion for our snowy adventures.',
    createdAt: '2024-06-18T12:00:00Z',
  },
  {
    _id: 'r-3',
    id: 'r-3',
    pet: mockPets[2],
    adopter: mockUsers[2],
    status: 'rejected',
    message: 'Calm household with no other pets.',
    createdAt: '2024-06-10T12:00:00Z',
  },
];
